name: Deploy mrubyedge docs

on:
  push:
    branches: [ "master" ]
    paths: [ "mrubyedge/**" ]
  pull_request:
    branches: [ "master" ]
    paths: [ "mrubyedge/**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run doc on mrubyedge
      run: cargo doc --no-deps -p mrubyedge
    - name: Add redirect index.html
      run: |
        cat > target/doc/index.html <<'EOF'
        <!DOCTYPE html>
        <html>
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=mrubyedge/">
            <link rel="canonical" href="mrubyedge/">
          </head>
          <body>
            <p>Redirecting to <a href="mrubyedge/">mrubyedge documentation</a>...</p>
          </body>
        </html>
        EOF
    - name: Upload
      uses: actions/upload-pages-artifact@v3
      with:
        path: target/doc

  deploy:
     needs: doc
     permissions:
       pages: write
       id-token: write
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
     runs-on: ubuntu-latest
     steps:
       - name: Deploy to GitHub Pages
         id: deployment
         uses: actions/deploy-pages@v4
